version: '3.8'

services:
  callback-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: local-callback:latest
    container_name: local-callback-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # 持久化数据库文件
      - callback_data:/app/backend/database
    restart: unless-stopped
    networks:
      - callback-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  callback_data:
    driver: local

networks:
  callback-network:
    driver: bridge